export const baseDatos = [
    {id: 1, nombreActivo:'aire acondicionando',tipo:"electronico", ubicacion:'recepcion', estado: 'activo' , button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 2, nombreActivo:'TV Samsung 55"',tipo:"electronico", ubicacion:'sala de juntas', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 3, nombreActivo:'TV LG 43"',tipo:"electronico", ubicacion:'oficina 1', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 4, nombreActivo:'TV Sony 65"',tipo:"electronico", ubicacion:'sala de conferencias', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 5, nombreActivo:'Celular iPhone 13',tipo:"electronico", ubicacion:'gerencia', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 6, nombreActivo:'Celular Samsung Galaxy S21',tipo:"electronico", ubicacion:'ventas', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 7, nombreActivo:'Celular Google Pixel 6',tipo:"electronico", ubicacion:'soporte tecnico', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 8, nombreActivo:'Celular Motorola G30',tipo:"electronico", ubicacion:'recepcion', estado: 'inactivo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 9, nombreActivo:'Laptop Dell XPS 13',tipo:"electronico", ubicacion:'diseño', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 10, nombreActivo:'Laptop HP Pavilion',tipo:"electronico", ubicacion:'contabilidad', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 11, nombreActivo:'Monitor LG 27"',tipo:"electronico", ubicacion:'oficina 2', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 12, nombreActivo:'Monitor Samsung 24"',tipo:"electronico", ubicacion:'oficina 3', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 13, nombreActivo:'Impresora HP LaserJet',tipo:"electronico", ubicacion:'almacen', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 14, nombreActivo:'Proyector Epson',tipo:"electronico", ubicacion:'sala de juntas', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 15, nombreActivo:'Router WiFi TP-Link',tipo:"electronico", ubicacion:'cuarto de equipos', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 16, nombreActivo:'Switch Cisco 48 puertos',tipo:"electronico", ubicacion:'cuarto de equipos', estado: 'activo',button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 17, nombreActivo:'Tablet Apple iPad Pro',tipo:"electronico", ubicacion:'area ejecutiva', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 18, nombreActivo:'Tablet Samsung Galaxy Tab',tipo:"electronico", ubicacion:'logistica', estado: 'inactivo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 19, nombreActivo:'Celular iPhone 14 Pro',tipo:"electronico", ubicacion:'marketing', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 20, nombreActivo:'TV Hisense 50"',tipo:"electronico", ubicacion:'cafeteria', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>},
    {id: 21, nombreActivo:'Celular OnePlus 11',tipo:"electronico", ubicacion:'desarrollo', estado: 'activo', button: <button>editar</button>, eliminar: <button>eliminar</button>}
];