export let baseDatos = [
    {id: 1, nombreActivo:'aire acondicionando', ubicacion:'recepcion', estado: 'activo'  },
    {id: 2, nombreActivo:'TV Samsung 55"', ubicacion:'sala de juntas', estado: 'activo'},
    {id: 3, nombreActivo:'TV LG 43"', ubicacion:'oficina 1', estado: 'activo'},
    {id: 4, nombreActivo:'TV Sony 65"', ubicacion:'sala de conferencias', estado: 'activo'},
    {id: 5, nombreActivo:'Celular iPhone 13', ubicacion:'gerencia', estado: 'activo'},
    {id: 6, nombreActivo:'Celular Samsung Galaxy S21', ubicacion:'ventas', estado: 'activo'},
    {id: 7, nombreActivo:'Celular Google Pixel 6', ubicacion:'soporte tecnico', estado: 'activo'},
    {id: 8, nombreActivo:'Celular Motorola G30', ubicacion:'recepcion', estado: 'inactivo'},
    {id: 9, nombreActivo:'Laptop Dell XPS 13', ubicacion:'diseño', estado: 'activo'},
    {id: 10, nombreActivo:'Laptop HP Pavilion', ubicacion:'contabilidad', estado: 'activo'},
    {id: 11, nombreActivo:'Monitor LG 27"', ubicacion:'oficina 2', estado: 'activo'},
    {id: 12, nombreActivo:'Monitor Samsung 24"', ubicacion:'oficina 3', estado: 'activo'},
    {id: 13, nombreActivo:'Impresora HP LaserJet', ubicacion:'almacen', estado: 'activo'},
    {id: 14, nombreActivo:'Proyector Epson', ubicacion:'sala de juntas', estado: 'activo'},
    {id: 15, nombreActivo:'Router WiFi TP-Link', ubicacion:'cuarto de equipos', estado: 'activo'},
    {id: 16, nombreActivo:'Switch Cisco 48 puertos', ubicacion:'cuarto de equipos', estado: 'activo'},
    {id: 17, nombreActivo:'Tablet Apple iPad Pro', ubicacion:'area ejecutiva', estado: 'activo'},
    {id: 18, nombreActivo:'Tablet Samsung Galaxy Tab', ubicacion:'logistica', estado: 'inactivo'},
    {id: 19, nombreActivo:'Celular iPhone 14 Pro', ubicacion:'marketing', estado: 'activo'},
    {id: 20, nombreActivo:'TV Hisense 50"', ubicacion:'cafeteria', estado: 'activo'},
    {id: 21, nombreActivo:'Celular OnePlus 11', ubicacion:'desarrollo', estado: 'activo'}
];